name: Deploy to GitHub Pages

on:
  push:
    branches: [master]   # 当推送到 master 时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # 或 20，与你本地一致

      - name: Install dependencies
        run: pnpm install          # 或 yarn / pnpm

      - name: Build
        run: npm run build   # 生成 dist 文件夹

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist          # Astro 默认输出目录
          publish_branch: gh-pages      # 推送到 gh-pages 分支